import { ReactNode, useState } from 'react';
import { ChevronDown, Palette, RotateCcw, Save, SlidersHorizontal } from 'lucide-react';
import { Button } from '@/components/ui';
import { ChartConfig, ChartCustomization, DataColumn, SeriesCustomization } from '@/types';
import { customizationPresets, palettes } from '@/utils/chartOptions';

interface Props {
  chart: ChartConfig;
  columns: DataColumn[];
  updateCustomization: (updates: Partial<ChartCustomization>) => void;
  updateSeries: (id: string, updates: Partial<SeriesCustomization>) => void;
  applyPreset: (name: string) => void;
  resetCustomization: () => void;
  savePreset: (name: string) => void;
}

type Section = 'general' | 'typography' | 'axes' | 'legend' | 'grid' | 'labels' | 'colors' | 'series' | 'specific';
const inputClass = 'w-full rounded-md border border-input bg-background px-2 py-1.5 text-sm outline-none focus:ring-2 focus:ring-ring';
const numberValue = (value: string) => Number(value) || 0;

export const CustomizationSidebar = ({ chart, columns, updateCustomization, updateSeries, applyPreset, resetCustomization, savePreset }: Props) => {
  const [open, setOpen] = useState<Record<Section, boolean>>({ general: true, typography: false, axes: false, legend: false, grid: false, labels: false, colors: true, series: true, specific: false });
  const customization = chart.customization;
  const change = <K extends keyof ChartCustomization>(key: K, value: ChartCustomization[K]) => updateCustomization({ [key]: value } as Partial<ChartCustomization>);
  const nested = <K extends 'typography' | 'margins' | 'xAxis' | 'yAxis' | 'legend' | 'grid' | 'dataLabels' | 'specific'>(key: K, value: Partial<ChartCustomization[K]>) => updateCustomization({ [key]: { ...customization[key], ...value } } as Partial<ChartCustomization>);
  const toggle = (name: Section) => setOpen((state) => ({ ...state, [name]: !state[name] }));
  const section = (name: Section, title: string, children: ReactNode) => <section className="border-b border-border pb-3"><button className="flex w-full items-center justify-between py-2 text-left font-semibold" onClick={() => toggle(name)}><span>{title}</span><ChevronDown className={`h-4 w-4 ${open[name] ? 'rotate-180' : ''}`} /></button>{open[name] && <div className="space-y-3 pt-2">{children}</div>}</section>;
  const field = (label: string, control: ReactNode) => <label className="block"><span className="mb-1 block text-xs font-medium text-muted-foreground">{label}</span>{control}</label>;
  const checkbox = (label: string, value: boolean, onChange: (value: boolean) => void) => <label className="flex items-center justify-between text-sm"><span>{label}</span><input type="checkbox" checked={value} onChange={(event) => onChange(event.target.checked)} className="h-4 w-4 accent-accent" /></label>;
  const range = (label: string, value: number, min: number, max: number, onChange: (value: number) => void) => field(`${label}: ${value}`, <input type="range" min={min} max={max} value={value} onChange={(event) => onChange(numberValue(event.target.value))} className="w-full accent-accent" />);
  const seriesLabel = (id: string) => columns.find((column) => column.id === id)?.name ?? 'Series';

  return <div className="space-y-3">
    <div className="flex items-center justify-between"><div className="flex items-center gap-2"><SlidersHorizontal className="h-4 w-4 text-accent" /><h2 className="font-semibold">Customize</h2></div><Button variant="ghost" size="sm" onClick={resetCustomization} title="Reset customization"><RotateCcw className="h-4 w-4" /></Button></div>
    {section('general', 'General', <>
      {field('Subtitle', <input className={inputClass} value={customization.subtitle} onChange={(event) => change('subtitle', event.target.value)} />)}
      {field('Description', <textarea className={inputClass} rows={2} value={customization.description} onChange={(event) => change('description', event.target.value)} />)}
      <div className="grid grid-cols-2 gap-2">{field('Width %', <input className={inputClass} type="number" value={customization.width} onChange={(event) => change('width', numberValue(event.target.value))} />)}{field('Height px', <input className={inputClass} type="number" value={customization.height} onChange={(event) => change('height', numberValue(event.target.value))} />)}</div>
      <div className="grid grid-cols-2 gap-2">{field('Background', <input className="h-9 w-full rounded border p-1" type="color" value={customization.background} onChange={(event) => change('background', event.target.value)} />)}{field('Text color', <input className="h-9 w-full rounded border p-1" type="color" value={customization.textColor} onChange={(event) => change('textColor', event.target.value)} />)}</div>
      <p className="text-xs font-medium text-muted-foreground">Margins</p><div className="grid grid-cols-4 gap-1">{(['top', 'right', 'bottom', 'left'] as const).map((side) => <input key={side} className={inputClass} aria-label={`${side} margin`} type="number" value={customization.margins[side]} onChange={(event) => nested('margins', { [side]: numberValue(event.target.value) })} />)}</div>
    </>)}
    {section('typography', 'Typography', <>
      {field('Font family', <select className={inputClass} value={customization.typography.fontFamily} onChange={(event) => nested('typography', { fontFamily: event.target.value })}><option>Inter, system-ui, sans-serif</option><option>Georgia, serif</option><option>ui-monospace, monospace</option><option>Verdana, sans-serif</option></select>)}
      <div className="grid grid-cols-2 gap-2">{(['titleSize', 'subtitleSize', 'axisFontSize', 'legendFontSize', 'dataLabelSize'] as const).map((key) => field(key.replace('Size', ' size'), <input key={key} className={inputClass} type="number" value={customization.typography[key]} onChange={(event) => nested('typography', { [key]: numberValue(event.target.value) })} />))}</div>
    </>)}
    {section('axes', 'Axes', <>
      <div className="rounded border border-border p-3"><p className="mb-2 font-medium">X-axis</p>{checkbox('Show axis', customization.xAxis.show, (value) => nested('xAxis', { show: value }))}{checkbox('Show labels', customization.xAxis.labels, (value) => nested('xAxis', { labels: value }))}{field('Title', <input className={inputClass} value={customization.xAxis.title} onChange={(event) => nested('xAxis', { title: event.target.value })} />)}{field('Position', <select className={inputClass} value={customization.xAxis.position} onChange={(event) => nested('xAxis', { position: event.target.value as 'top' | 'bottom' })}><option value="bottom">Bottom</option><option value="top">Top</option></select>)}{range('Rotation', customization.xAxis.rotation, -90, 90, (value) => nested('xAxis', { rotation: value }))}</div>
      <div className="rounded border border-border p-3"><p className="mb-2 font-medium">Y-axis</p>{checkbox('Show axis', customization.yAxis.show, (value) => nested('yAxis', { show: value }))}{checkbox('Show labels', customization.yAxis.labels, (value) => nested('yAxis', { labels: value }))}{field('Title', <input className={inputClass} value={customization.yAxis.title} onChange={(event) => nested('yAxis', { title: event.target.value })} />)}{field('Number format', <select className={inputClass} value={customization.yAxis.numberFormat} onChange={(event) => nested('yAxis', { numberFormat: event.target.value as ChartCustomization['yAxis']['numberFormat'] })}><option>auto</option><option>number</option><option>currency</option><option>percentage</option></select>)}</div>
    </>)}
    {section('legend', 'Legend', <><>{checkbox('Show legend', customization.legend.show, (value) => nested('legend', { show: value }))}</><div className="grid grid-cols-2 gap-2">{field('Position', <select className={inputClass} value={customization.legend.position} onChange={(event) => nested('legend', { position: event.target.value as ChartCustomization['legend']['position'] })}><option>top</option><option>bottom</option><option>left</option><option>right</option></select>)}{field('Orientation', <select className={inputClass} value={customization.legend.orientation} onChange={(event) => nested('legend', { orientation: event.target.value as 'horizontal' | 'vertical' })}><option>horizontal</option><option>vertical</option></select>)}</div></>)}
    {section('grid', 'Grid', <>{checkbox('Show grid', customization.grid.show, (value) => nested('grid', { show: value }))}{checkbox('X grid', customization.grid.x, (value) => nested('grid', { x: value }))}{checkbox('Y grid', customization.grid.y, (value) => nested('grid', { y: value }))}{field('Grid color', <input className="h-9 w-full rounded border p-1" type="color" value={customization.gridColor} onChange={(event) => change('gridColor', event.target.value)} />)}{range('Opacity', customization.grid.opacity * 100, 0, 100, (value) => nested('grid', { opacity: value / 100 }))}</>)}
    {section('labels', 'Data labels', <><>{checkbox('Show labels', customization.dataLabels.show, (value) => nested('dataLabels', { show: value }))}</><div className="grid grid-cols-2 gap-2">{field('Position', <select className={inputClass} value={customization.dataLabels.position} onChange={(event) => nested('dataLabels', { position: event.target.value as ChartCustomization['dataLabels']['position'] })}><option>top</option><option>inside</option><option>outside</option></select>)}{field('Format', <select className={inputClass} value={customization.dataLabels.numberFormat} onChange={(event) => nested('dataLabels', { numberFormat: event.target.value as ChartCustomization['dataLabels']['numberFormat'] })}><option>auto</option><option>number</option><option>percentage</option></select>)}{field('Decimals', <input className={inputClass} type="number" value={customization.dataLabels.decimals} onChange={(event) => nested('dataLabels', { decimals: numberValue(event.target.value) })} />)}</div></>)}
    {section('colors', 'Colors & presets', <><div className="flex items-center gap-2"><Palette className="h-4 w-4 text-accent" />{field('Theme', <select className={inputClass} value={customization.palette} onChange={(event) => applyPreset(event.target.value)}><option value="">Choose theme</option>{Object.keys(palettes).map((name) => <option key={name}>{name}</option>)}{Object.keys(customizationPresets).filter((name) => !palettes[name]).map((name) => <option key={name}>{name}</option>)}</select>)}</div><Button variant="outline" size="sm" className="w-full" onClick={() => savePreset(window.prompt('Preset name') ?? '')}><Save className="mr-2 h-4 w-4" />Save local preset</Button><div className="grid grid-cols-5 gap-1">{customization.colors.map((color) => <span key={color} className="h-5 rounded" style={{ backgroundColor: color }} />)}</div></>)}
    {section('series', 'Series editor', <div className="space-y-4">{chart.mapping.valueColumnIds.map((id, index) => { const style = customization.series[id] ?? { visible: true, color: customization.colors[index % customization.colors.length], lineWidth: 2, lineType: 'solid' as const, symbol: 'circle' as const, symbolSize: 8, barWidth: 55, opacity: 1, areaFill: false, labelVisible: false }; return <div key={id} className="rounded border border-border p-3">{checkbox(`${seriesLabel(id)} visible`, style.visible, (value) => updateSeries(id, { visible: value }))}{field('Series name', <input className={inputClass} value={style.name ?? seriesLabel(id)} onChange={(event) => updateSeries(id, { name: event.target.value })} />)}{field('Color', <input className="h-9 w-full rounded border p-1" type="color" value={style.color} onChange={(event) => updateSeries(id, { color: event.target.value })} />)}{range('Line width', style.lineWidth, 1, 12, (value) => updateSeries(id, { lineWidth: value }))}{range('Symbol size', style.symbolSize, 0, 24, (value) => updateSeries(id, { symbolSize: value }))}{range('Bar width', style.barWidth, 10, 100, (value) => updateSeries(id, { barWidth: value }))}{range('Opacity', style.opacity * 100, 10, 100, (value) => updateSeries(id, { opacity: value / 100 }))}{checkbox('Area fill', style.areaFill, (value) => updateSeries(id, { areaFill: value }))}{checkbox('Data label', style.labelVisible, (value) => updateSeries(id, { labelVisible: value }))}</div>; })}</div>)}
    {section('specific', 'Chart-specific', <>{(chart.type === 'bar' || chart.type === 'horizontal-bar' || chart.type.includes('stacked')) && <>{range('Bar width', customization.specific.barWidth, 10, 100, (value) => nested('specific', { barWidth: value }))}{range('Border radius', customization.specific.borderRadius, 0, 24, (value) => nested('specific', { borderRadius: value }))}{checkbox('Stack series', customization.specific.stacked, (value) => nested('specific', { stacked: value }))}</>}{(chart.type === 'line' || chart.type === 'area' || chart.type === 'stacked-area') && <>{checkbox('Smooth lines', customization.specific.smooth, (value) => nested('specific', { smooth: value }))}{checkbox('Symbols', customization.specific.symbols, (value) => nested('specific', { symbols: value }))}{checkbox('Area fill', customization.specific.areaFill, (value) => nested('specific', { areaFill: value }))}</>}{(chart.type === 'pie' || chart.type === 'doughnut') && <>{range('Inner radius', customization.specific.pieInnerRadius, 0, 90, (value) => nested('specific', { pieInnerRadius: value }))}{range('Outer radius', customization.specific.pieOuterRadius, 20, 95, (value) => nested('specific', { pieOuterRadius: value }))}{range('Start angle', customization.specific.pieStartAngle, 0, 360, (value) => nested('specific', { pieStartAngle: value }))}</>}{chart.type === 'radar' && range('Radar radius', customization.specific.radarRadius, 20, 95, (value) => nested('specific', { radarRadius: value }))}{chart.type === 'gauge' && <><div className="grid grid-cols-2 gap-2">{field('Min', <input className={inputClass} type="number" value={customization.specific.gaugeMin} onChange={(event) => nested('specific', { gaugeMin: numberValue(event.target.value) })} />)}{field('Max', <input className={inputClass} type="number" value={customization.specific.gaugeMax} onChange={(event) => nested('specific', { gaugeMax: numberValue(event.target.value) })} />)}</div>{range('Start angle', customization.specific.gaugeStartAngle, -360, 360, (value) => nested('specific', { gaugeStartAngle: value }))}{range('End angle', customization.specific.gaugeEndAngle, -360, 360, (value) => nested('specific', { gaugeEndAngle: value }))}</>}</>)}
  </div>;
};
