import * as echarts from 'echarts';
import { jsPDF } from 'jspdf';
import { ChartConfig, DataTable } from '@/types';
import { buildChartOption } from './chartOptions';

export type ImageFormat = 'png' | 'jpeg' | 'svg';
export interface ExportSettings {
  format: ImageFormat;
  width: number;
  height: number;
  pixelRatio: number;
  background: string;
  transparent: boolean;
  quality: number;
  filename: string;
}

const dataUrlBlob = async (dataUrl: string) => (await fetch(dataUrl)).blob();
const createRenderer = (table: DataTable, config: ChartConfig, width: number, height: number, renderer: 'canvas' | 'svg') => {
  const element = document.createElement('div');
  element.style.cssText = `position:fixed;left:-10000px;top:0;width:${width}px;height:${height}px;pointer-events:none;`;
  document.body.appendChild(element);
  const instance = echarts.init(element, undefined, { renderer, width, height });
  instance.setOption(buildChartOption(table, config), true);
  return { element, instance };
};

export const chartDataUrl = (table: DataTable, config: ChartConfig, settings: Pick<ExportSettings, 'format' | 'width' | 'height' | 'pixelRatio' | 'background' | 'transparent' | 'quality'>): string => {
  const { element, instance } = createRenderer(table, config, settings.width, settings.height, settings.format === 'svg' ? 'svg' : 'canvas');
  try {
    if (settings.format === 'jpeg') {
      const canvas = instance.getDom().querySelector('canvas');
      if (canvas) return canvas.toDataURL('image/jpeg', settings.quality);
    }
    return instance.getDataURL({ type: settings.format, pixelRatio: settings.pixelRatio, backgroundColor: settings.transparent ? undefined : settings.background });
  } finally {
    instance.dispose();
    element.remove();
  }
};

export const downloadDataUrl = (dataUrl: string, filename: string) => {
  const link = document.createElement('a');
  link.href = dataUrl;
  link.download = filename;
  link.click();
};

export const csvText = (table: DataTable) => {
  const escape = (value: string) => {
    const normalized = value.replace(/"/g, '""');
    return /[",\n\r]/.test(normalized) ? `"${normalized}"` : normalized;
  };
  const headers = table.columns.map((column) => escape(column.name)).join(',');
  const rows = table.rows.map((row) => table.columns.map((_, index) => escape(row[index] ?? '')).join(','));
  return `\uFEFF${[headers, ...rows].join('\n')}`;
};

export const downloadCsv = (table: DataTable, filename: string) => downloadDataUrl(`data:text/csv;charset=utf-8,${encodeURIComponent(csvText(table))}`, filename);

export const downloadPdf = (dataUrl: string, config: ChartConfig, settings: Pick<ExportSettings, 'width' | 'height' | 'background' | 'transparent'>, filename: string, orientation: 'portrait' | 'landscape', pageSize: 'a4' | 'letter' | 'a3') => {
  const pdf = new jsPDF({ orientation, unit: 'pt', format: pageSize });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 36;
  const imageWidth = pageWidth - margin * 2;
  const imageHeight = Math.min(pageHeight - 130, imageWidth * settings.height / settings.width);
  pdf.setFillColor(settings.transparent ? 255 : parseInt(settings.background.slice(1, 3), 16), settings.transparent ? 255 : parseInt(settings.background.slice(3, 5), 16), settings.transparent ? 255 : parseInt(settings.background.slice(5, 7), 16));
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');
  pdf.setTextColor(30, 41, 59);
  pdf.setFontSize(18);
  pdf.text(config.title, margin, margin + 4);
  if (config.customization.subtitle) { pdf.setFontSize(10); pdf.text(config.customization.subtitle, margin, margin + 20); }
  pdf.addImage(dataUrl, 'PNG', margin, margin + 34, imageWidth, imageHeight, undefined, 'FAST');
  pdf.setFontSize(8);
  pdf.setTextColor(100, 116, 139);
  pdf.text(`Generated by ChartGen · ${new Date().toLocaleDateString()}`, margin, pageHeight - margin / 2);
  pdf.save(filename);
};

export const copyChartImage = async (dataUrl: string) => {
  if (!navigator.clipboard || typeof ClipboardItem === 'undefined') throw new Error('Image clipboard is not supported in this browser.');
  const blob = await dataUrlBlob(dataUrl);
  await navigator.clipboard.write([new ClipboardItem({ [blob.type]: blob })]);
};
export const copySvg = async (svgDataUrl: string) => { if (!navigator.clipboard?.writeText) throw new Error('Clipboard text is not supported in this browser.'); await navigator.clipboard.writeText(await (await fetch(svgDataUrl)).text()); };
export const copyData = async (table: DataTable) => { if (!navigator.clipboard?.writeText) throw new Error('Clipboard text is not supported in this browser.'); await navigator.clipboard.writeText(csvText(table).replace(/^\uFEFF/, '')); };
export const copyProjectData = async (table: DataTable, projectName?: string) => { if (!navigator.clipboard?.writeText) throw new Error('Clipboard text is not supported in this browser.'); await navigator.clipboard.writeText(JSON.stringify({ projectName, dataset: table }, null, 2)); };
export const copyChartConfig = async (config: ChartConfig, projectName?: string) => { if (!navigator.clipboard?.writeText) throw new Error('Clipboard text is not supported in this browser.'); await navigator.clipboard.writeText(JSON.stringify({ projectName, chart: config }, null, 2)); };
export const shareChart = async (config: ChartConfig, projectName?: string) => { const payload = JSON.stringify({ projectName, chart: config }, null, 2); if (navigator.share) { await navigator.share({ title: config.title, text: `Chart configuration for ${config.title}`, url: window.location.href }); return 'Shared using your browser.'; } if (navigator.clipboard?.writeText) { await navigator.clipboard.writeText(payload); return 'Chart configuration copied. Server sharing is not available yet.'; } throw new Error('Sharing is not supported in this browser.'); };
